bionic_university_delivery:
    resource: "@BionicUniversityDeliveryBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

bionic_university_web:
    resource: "@BionicUniversityWebBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|ru

bionic_university_catalog:
    resource: "@BionicUniversityCatalogBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|ru

