bionic_university_web:
    resource: "@BionicUniversityWebBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|ru

bionic_university_catalog:
    resource: "@BionicUniversityCatalogBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|ru

bionic_university_product:
    resource: "@BionicUniversityProductBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|ru

#bionic_university_product_status:
#    resource: "@BionicUniversityProductBundle/Controller/Product/"
#    type:     annotation
#    prefix:   /{_locale}
#    requirements:
#        _locale: en|ru
