services:
    category_extension:
        class: BionicUniversity\Bundle\CatalogBundle\Twig\CategoryExtension
        calls:
            - [setOm, [@doctrine.orm.default_entity_manager]]
        tags:
            - { name: twig.extension }